version: "3.9"
services:
  php:
    image: medial/symfony:latest
    container_name: medial_php
    ports:
      - 80:80
      - 8000:8000
    networks:
      frontend:
      backend:
    volumes:
      - ./symfony/:/var/www/html/
  mariadb:
    image: mariadb:latest
    container_name: medial_mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
    - ./data/db/:/var/lib/mysql/
  node:
    build:
      context: ./containers/node/
    container_name: medial_node
    networks:
      frontend:
      backend:
    volumes:
      - ./symfony/:/home/node/app/
networks:
  frontend:
  backend: